server:
  port: 8764

spring:
  application:
    name: service-demo
  redis:
    host: 118.190.107.186
    post: 6379
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://118.190.107.186:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 #发送给服务端的心跳频率
    leaseExpirationDurationInSeconds: 10 #等待下一次心跳的时间
