server:
  port: 8081

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: service-hi
        uri: lb://SERVICE-HI
        predicates:
          - Path=/service-hi/**
        filters:
          - StripPrefix=1
          - RequestTime=true
      - id: service-hei
        uri: lb://SERVICE-HEI
        predicates:
          - Path=/service-hei/**
        filters:
          - StripPrefix=1
          - RequestTime=true
      - id: service-file
        uri: lb://SERVICE-FILE
        predicates:
          - Path=/service-file/**
        filters:
          - StripPrefix=1
          - RequestTime=true

eureka:
  client:
    service-url:
      defaultZone: http://118.190.107.186:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 #发送给服务端的心跳频率
    leaseExpirationDurationInSeconds: 10 #等待下一次心跳的时间
logging:
  level:
    org.springframework.cloud.gateway: debug



