server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://118.190.107.186:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 #发送给服务端的心跳频率
    leaseExpirationDurationInSeconds: 10 #等待下一次心跳的时间